# Generated by Django 4.1.7 on 2023-04-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_productimage_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
