# Generated by Django 4.1.7 on 2023-04-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
